<a href="https://colab.research.google.com/github/Amitsharma405/Amit_projects/blob/main/Assignment_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ques.1  Create a NumPy array 'arr' of integers from 0 to 5 and print its data type?


In [ ]:
import numpy as np

arr = np.arange(6)

print(arr)
print(arr.dtype)

[0 1 2 3 4 5]
int64


ques.2  Given a NumPy array 'arr', check if its data type is float64.
   arr = np.array([1.5, 2.6, 3.7])

In [ ]:
import numpy as np

arr = np.array([1.5, 2.6, 3.7])

print(arr.dtype == np.float64)

True


ques.3  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.?

In [ ]:
import numpy as np

arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

print(arr)
print(arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
complex128


ques.4 Convert an existing NumPy array 'arr' of integers to float32 data type?

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)

[1. 2. 3. 4.]
float32


ques.5  Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision?

In [ ]:
import numpy as np

arr = np.array([1.123456789, 2.987654321, 3.456789123], dtype=np.float64)

arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)

[1.1234568 2.9876542 3.456789 ]
float32


ques.6 Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type?

In [ ]:
import numpy as np

def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([[1, 2, 3], [4, 5, 6]])

shape, size, dtype = array_attributes(arr)

print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)

Shape: (2, 3)
Size: 6
Data type: int64


ques.7 Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.?

In [ ]:
import numpy as np

def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])

dim = array_dimension(arr)
print("Dimensionality:", dim)

Dimensionality: 2


ques.8  Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes?

In [ ]:
import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

arr = np.array([1, 2, 3, 4], dtype=np.int32)

item_size, total_size = item_size_info(arr)

print("Item size (bytes):", item_size)
print("Total size (bytes):", total_size)

Item size (bytes): 4
Total size (bytes): 16


ques.9 Create a function array_strides that takes a NumPy array as input and returns the strides of the array?

In [ ]:
import numpy as np

def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Strides:", array_strides(arr))

Strides: (24, 8)


ques.10  Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array?

In [ ]:
import numpy as np

def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])

shape, strides = shape_stride_relationship(arr)

print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (24, 8)


ques.11 Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements?

In [ ]:
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

arr = create_zeros_array(5)
print(arr)

[0. 0. 0. 0. 0.]


ques.12  Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.?

In [ ]:
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

matrix = create_ones_matrix(3, 4)
print(matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


ques.13 Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.?

In [ ]:
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

arr = generate_range_array(0, 10, 2)
print(arr)

[0 2 4 6 8]


ques.14  Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).?

In [ ]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

arr = generate_linear_space(0.0, 1.0, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


ques.15 Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.?

In [ ]:
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

identity_matrix = create_identity_matrix(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


ques.16 Write a function that takes a Python list and converts it into a NumPy array?

In [ ]:
import numpy as np

def list_to_numpy(lst):
    return np.array(lst)

py_list = [1, 2, 3, 4, 5]
arr = list_to_numpy(py_list)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


ques.17 Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data?

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

arr_view = arr.view()
print("View of array:", arr_view)

arr_view[0] = 100

print("Modified view:", arr_view)
print("Original array after modifying view:", arr)

Original array: [1 2 3 4 5]
View of array: [1 2 3 4 5]
Modified view: [100   2   3   4   5]
Original array after modifying view: [100   2   3   4   5]


ques.18 Write a function that takes two NumPy arrays and concatenates them along a specified axis?

In [ ]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

concat_axis0 = concatenate_arrays(a, b, axis=0)
print("Concatenate along axis 0:\n", concat_axis0)

concat_axis1 = concatenate_arrays(a, b, axis=1)
print("Concatenate along axis 1:\n", concat_axis1)

Concatenate along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


ques.19 Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.?



In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])
h_concat = np.concatenate((arr1, arr2), axis=1)

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Horizontally concatenated array:\n", h_concat)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8]
 [ 9 10]]
Horizontally concatenated array:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


ques.20 Write a function that vertically stacks multiple NumPy arrays given as a list.?

In [ ]:
import numpy as np

def vertical_stack_arrays(array_list):
    return np.vstack(array_list)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

stacked_array = vertical_stack_arrays([arr1, arr2, arr3])
print("Vertically stacked array:\n", stacked_array)

Vertically stacked array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


ques.21 . Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.?

In [ ]:
import numpy as np

def create_integer_range(start, stop, step=1):

    if step > 0:
        stop_inclusive = stop + 1
    else:
        stop_inclusive = stop - 1

    return np.arange(start, stop_inclusive, step)

arr = create_integer_range(1, 10, 2)
print(arr)

[1 3 5 7 9]


ques.22 Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).?

In [ ]:
import numpy as np

def generate_equally_spaced():

    return np.linspace(0, 1, 10)

arr = generate_equally_spaced()
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


ques.23 Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).?

In [ ]:
import numpy as np

def generate_log_space():

    return np.logspace(0, 3, 5)  # 10^0 = 1, 10^3 = 1000

arr = generate_log_space()
print(arr)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


ques.24 Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.?

In [ ]:
import numpy as np
import pandas as pd

arr = np.random.randint(1, 101, size=(5, 3))

df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

print("NumPy array:\n", arr)
print("\nPandas DataFrame:\n", df)

NumPy array:
 [[ 1 62 76]
 [24 18 75]
 [67 60 10]
 [29 90 96]
 [ 5 45 13]]

Pandas DataFrame:
     A   B   C
0   1  62  76
1  24  18  75
2  67  60  10
3  29  90  96
4   5  45  13


ques.25 Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.?

In [ ]:
import pandas as pd
import numpy as np

def replace_negatives_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {
    'A': [5, -3, 7, -1],
    'B': [-2, 8, -6, 4]
}
df = pd.DataFrame(data)

print("Original DataFrame:\n", df)

df_modified = replace_negatives_with_zero(df, 'A')
print("\nModified DataFrame:\n", df_modified)

Original DataFrame:
    A  B
0  5 -2
1 -3  8
2  7 -6
3 -1  4

Modified DataFrame:
    A  B
0  5 -2
1  0  8
2  7 -6
3  0  4


ques.26 Access the 3rd element from the given NumPy array.
 arr = np.array([10, 20, 30, 40, 50])?

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

third_element = arr[2]

print("3rd element:", third_element)

3rd element: 30


ques.27 Retrieve the element at index (1, 2) from the 2D NumPy array.
 arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])?

In [ ]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
element = arr_2d[1, 2]
print(element)

6


ques.28 Using boolean indexing, extract elements greater than 5 from the given NumPy array.
 arr = np.array([3, 8, 2, 10, 5, 7])

In [ ]:
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

result = arr[arr > 5]
print(result)

[ 8 10  7]


ques.29 Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
  arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced = arr[2:6]
print(sliced)

[3 4 5 6]


ques.30 Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
  arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


In [ ]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


ques.31 .Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.?

In [ ]:
import numpy as np

def extract_elements_by_indices(arr_2d, indices):
    rows = indices[:, 0]
    cols = indices[:, 1]
    return arr_2d[rows, cols]

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([[0, 1], [1, 2], [2, 0]])  # Extract arr[0,1], arr[1,2], arr[2,0]
result = extract_elements_by_indices(arr_2d, indices)
print(result)

[2 6 7]


ques.32 Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing?

In [ ]:
import numpy as np

def filter_greater_than(arr, threshold):


    return arr[arr > threshold]

arr = np.array([3, 8, 2, 10, 5, 7])
threshold = 5
result = filter_greater_than(arr, threshold)
print(result)

[ 8 10  7]


ques.33 Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension?

In [ ]:
import numpy as np

def extract_3d_elements(arr_3d, idx_depth, idx_row, idx_col):

    return arr_3d[idx_depth, idx_row, idx_col]


ques.34 Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing?

In [ ]:
import numpy as np

def filter_two_conditions(arr, cond1, cond2):
    """
    Return elements from a 1D NumPy array that satisfy both conditions using boolean indexing.

    Parameters:
    arr (np.ndarray): 1D NumPy array
    cond1 (callable): First condition function, e.g., lambda x: x > 5
    cond2 (callable): Second condition function, e.g., lambda x: x % 2 == 0

    Returns:
    np.ndarray: Array of elements satisfying both conditions
    """
    return arr[cond1(arr) & cond2(arr)]


arr = np.array([1, 4, 6, 8, 9, 12])
result = filter_two_conditions(arr, lambda x: x > 5, lambda x: x % 2 == 0)
print(result)

[ 6  8 12]


ques.35 Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays?

In [ ]:
import numpy as np

def extract_2d_elements(arr_2d, row_indices, col_indices):
       return arr_2d[row_indices, col_indices]

ques.36 Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.?


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5
print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


ques.37 Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting?

In [ ]:
import numpy as np

arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9,10,11,12]])

result = arr1.T * arr2
print(result)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


ques.38 Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting?

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100,110,120]])
result = arr1.T + arr2
print(result)

[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


ques.39 Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcastin?

In [ ]:
import numpy as np


arr1 = np.array([[1],
                 [2],
                 [3]])

arr2 = np.array([[10, 20, 30]])

result = arr1 + arr2
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


ques.40  Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility?

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[10, 20],
                 [30, 40]])


result = arr1[:, :, np.newaxis] * arr2[:, np.newaxis, :]
print(result)
print(result.shape)

[[[ 10  20]
  [ 20  40]
  [ 30  60]]

 [[120 160]
  [150 200]
  [180 240]]]
(2, 3, 2)


ques.41 Calculate column wise mean for the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

col_mean = np.mean(arr, axis=0)
print(col_mean)

[2.5 3.5 4.5]


ques.42 Find maximum value in each row of the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

row_max = np.max(arr, axis=1)
print(row_max)

[3 6]


ques.43 For the given array, find indices of maximum value in each column.
  arr = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

col_max_indices = np.argmax(arr, axis=0)
print(col_max_indices)

[1 1 1]


ques.44 For the given array, apply custom function to calculate moving sum along rows.
  arr = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

def moving_sum_rows(array):
    """
    Calculate moving sum along rows of a 2D array.

    Parameters:
    array (np.ndarray): 2D NumPy array

    Returns:
    np.ndarray: Moving sum along each row
    """
    return np.cumsum(array, axis=1)

result = moving_sum_rows(arr)
print(result)

[[ 1  3  6]
 [ 4  9 15]]


ques.45  In the given array, check if all elements in each column are even.
  arr = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:
import numpy as np

arr = np.array([[2, 4, 6],
                [3, 5, 7]])

all_even_cols = np.all(arr % 2 == 0, axis=0)
print(all_even_cols)

[False False False]


ques.46 Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
 original_array = np.array([1, 2, 3, 4, 5, 6])



In [ ]:
import numpy as np

def reshape_array(arr, m, n):
    """
    Reshape a 1D NumPy array into a matrix with m rows and n columns.

    Parameters:
    arr (np.ndarray): Original 1D array
    m (int): Number of rows
    n (int): Number of columns

    Returns:
    np.ndarray: Reshaped 2D matrix
    """
    if arr.size != m * n:
        raise ValueError("The total elements do not match m * n")
    return arr.reshape(m, n)

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_matrix = reshape_array(original_array, 2, 3)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


ques.47  Create a function that takes a matrix as input and returns the flattened array.
   input_matrix = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
import numpy as np

def flatten_matrix(matrix):
    """
    Flatten a 2D NumPy array into a 1D array.

    Parameters:
    matrix (np.ndarray): Input 2D array

    Returns:
    np.ndarray: Flattened 1D array
    """
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


ques.48 Write a function that concatenates two given arrays along a specified axis.
 array1 = np.array([[1, 2], [3, 4]])
 array2 = np.array([[5, 6], [7, 8]])

In [ ]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    """
    Concatenate two arrays along the specified axis.

    Parameters:
    arr1 (np.ndarray): First array
    arr2 (np.ndarray): Second array
    axis (int): Axis along which to concatenate (0 for rows, 1 for columns)

    Returns:
    np.ndarray: Concatenated array
    """
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])

result_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenate along axis 0:\n", result_axis0)

result_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenate along axis 1:\n", result_axis1)



Concatenate along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


ques.49 Create a function that splits an array into multiple sub-arrays along a specified axis
 original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [ ]:
import numpy as np

def split_array(arr, num_splits, axis=0):
    """
    Split a NumPy array into multiple sub-arrays along a specified axis.

    Parameters:
    arr (np.ndarray): Input array
    num_splits (int): Number of sub-arrays to split into
    axis (int): Axis along which to split (0 for rows, 1 for columns)

    Returns:
    list of np.ndarray: List containing the sub-arrays
    """
    return np.array_split(arr, num_splits, axis=axis)

original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

sub_arrays_rows = split_array(original_array, 3, axis=0)
print("Split along rows:")
for sub in sub_arrays_rows:
    print(sub)

sub_arrays_cols = split_array(original_array, 3, axis=1)
print("\nSplit along columns:")
for sub in sub_arrays_cols:
    print(sub)

Split along rows:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split along columns:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


ques.50  Write a function that inserts and then deletes elements from a given array at specified indices
  original_array = np.array([1, 2, 3, 4, 5])
  indices_to_insert = [2, 4]
  values_to_insert = [10, 11]
  indices_to_delete = [1, 3]

In [ ]:
import numpy as np

def insert_and_delete(arr, insert_indices, insert_values, delete_indices):
    """
    Insert values at specified indices and then delete elements at specified indices.

    Parameters:
    arr (np.ndarray): Original array
    insert_indices (list or np.ndarray): Indices to insert values
    insert_values (list or np.ndarray): Values to insert
    delete_indices (list or np.ndarray): Indices to delete

    Returns:
    np.ndarray: Modified array after insertion and deletion
    """
    arr_modified = np.insert(arr, insert_indices, insert_values)

    arr_modified = np.delete(arr_modified, delete_indices)

    return arr_modified

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result)

[ 1 10  4 11  5]


ques.51 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2?

In [ ]:
import numpy as np

arr1 = np.random.randint(0, 20, size=10)

arr2 = np.arange(1, 11)

result = arr1 + arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise addition:", result)

arr1: [13  6  0 17  0 17 16  0  6  5]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise addition: [14  8  3 21  5 23 23  8 15 15]


ques.52 Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise?

In [ ]:
import numpy as np

arr1 = np.arange(10, 0, -1)

arr2 = np.arange(1, 11)

result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("arr1 - arr2:", result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
arr1 - arr2: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


ques.53 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.?

In [ ]:
import numpy as np

arr1 = np.random.randint(0, 10, size=5)

arr2 = np.arange(1, 6)

result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise multiplication:", result)

arr1: [6 4 4 3 9]
arr2: [1 2 3 4 5]
Element-wise multiplication: [ 6  8 12 12 45]


ques.54 Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.?

In [ ]:
import numpy as np

arr1 = np.arange(2, 11, 2)

arr2 = np.arange(1, 6)

result = arr1 / arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("arr1 / arr2:", result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
arr1 / arr2: [2. 2. 2. 2. 2.]


ques.55 Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise?

In [ ]:
import numpy as np

arr1 = np.arange(1, 6)

arr2 = arr1[::-1]

result = arr1 ** arr2
print("arr1:", arr1)
print("arr2:", arr2)
print("arr1 ** arr2:", result)

arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
arr1 ** arr2: [ 1 16 27 16  5]


ques.56 Write a function that counts the occurrences of a specific substring within a NumPy array of strings
 arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])


In [ ]:
import numpy as np

def count_substring(arr, substring):
    return np.sum(np.char.find(arr, substring) != -1)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
result = count_substring(arr, 'hello')
print(result)

3


ques.57 Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
   arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])


In [ ]:
import numpy as np

def extract_uppercase(arr):
    return np.array([''.join([c for c in s if c.isupper()]) for s in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase(arr)
print(result)

['H' 'W' 'OAI' 'GPT']


ques.58 Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


In [ ]:
import numpy as np

def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = replace_substring(arr, 'apple', 'fruit')
print(result)

['fruit' 'banana' 'grape' 'pinefruit']


ques.59 Write a function that concatenates strings in a NumPy array element-wise
 arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [ ]:
import numpy as np

def concatenate_arrays(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_arrays(arr1, arr2)
print(result)

['HelloOpen' 'WorldAI']


ques.60 Write a function that finds the length of the longest string in a NumPy array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
  arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


In [ ]:
import numpy as np

def longest_string_length(arr):
    return np.max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = longest_string_length(arr)
print(result)

9


ques.61  Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.


In [ ]:
import numpy as np

def compute_statistics():
    data = np.random.randint(1, 1001, size=100)

    mean = np.mean(data)
    median = np.median(data)
    variance = np.var(data)
    std_dev = np.std(data)

    return data, mean, median, variance, std_dev

data, mean, median, variance, std_dev = compute_statistics()

print("Dataset:\n", data)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Dataset:
 [357  84 899 228 935 341 554  94 325 444 286 957 215 333 227  42 561 640
 950 550 450 583 462 946 695 982  25 743 896 161 985 941 266 270 103 272
 573 569 128 231 455 746 199 928 351 350 953 716 583 365 208 358 618 687
 590  42 479 674 998 790 600 774 223 215 500   2 413 260 556 619 339 883
  87 502 156 157 912 252 951 437 637 837  56 517 458 940 578 258 841 566
 927 572 603 728 406 143 184 755 516 357]
Mean: 501.1
Median: 501.0
Variance: 79899.47
Standard Deviation: 282.6649429978893


ques.62  Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset

In [ ]:
import numpy as np

def compute_percentiles():
    data = np.random.randint(1, 101, size=50)

    p25 = np.percentile(data, 25)
    p75 = np.percentile(data, 75)

    return data, p25, p75

data, p25, p75 = compute_percentiles()

print("Dataset:\n", data)
print("25th Percentile:", p25)
print("75th Percentile:", p75)

Dataset:
 [ 14  41  76  97 100  90  95  87  60  14  18  52  93  76  29  24  46  53
  67  31   2  63  89  10  24  77  46  77  37  94  66   4  70  64   6  58
  77  83  71  17  49  84  51  52  88  88  53  97  77  37]
25th Percentile: 37.0
75th Percentile: 81.5


ques.63 Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [ ]:
import numpy as np

def compute_correlation():
    x = np.random.randint(1, 100, size=50)
    y = np.random.randint(1, 100, size=50)

    corr_matrix = np.corrcoef(x, y)

    corr_coefficient = corr_matrix[0, 1]

    return x, y, corr_coefficient

x, y, corr = compute_correlation()

print("Array X:\n", x)
print("Array Y:\n", y)
print("Correlation Coefficient:", corr)


Array X:
 [ 2 20  8 88 23 60 20 94 83 48 18 42 96 82 52  9 17 89 30 15 18 18 59 20
 64 58  8 81 67 12 22 47  3 59 65 65 16 45 86 18 34 98 73 19 76 74 66 78
 23 56]
Array Y:
 [25 63 37 80 63 41 86 98 99 26 19 52  9 14 20 29 50 86 38 69 61 32  9 74
 95 37 69 10 67 56 39 82 27 28 65 71 96 89 58 76 25 81 31 60 80 96 43 58
  5 74]
Correlation Coefficient: 0.1679167533661713


ques.64 Create two matrices and perform matrix multiplication using NumPy's `dot` function

In [ ]:
import numpy as np

def matrix_multiplication():
    A = np.array([[1, 2, 3],
                  [4, 5, 6]])

    B = np.array([[7, 8],
                  [9, 10],
                  [11, 12]])

    result = np.dot(A, B)

    return A, B, result

A, B, result = matrix_multiplication()

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Result (A · B):\n", result)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Result (A · B):
 [[ 58  64]
 [139 154]]


ques.65  Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.?

In [ ]:
import numpy as np

def compute_stats():
    data = np.random.randint(10, 1001, size=50)

    p10 = np.percentile(data, 10)
    p50 = np.percentile(data, 50)
    p90 = np.percentile(data, 90)

    q1 = np.percentile(data, 25)
    q3 = np.percentile(data, 75)

    return data, p10, p50, p90, q1, q3

data, p10, p50, p90, q1, q3 = compute_stats()

print("Dataset:\n", data)
print("10th Percentile:", p10)
print("50th Percentile (Median):", p50)
print("90th Percentile:", p90)
print("First Quartile (Q1):", q1)
print("Third Quartile (Q3):", q3)

Dataset:
 [ 55 720 622 589 787 125 721 974 660 859 419 854 987 787 478 105 773 987
 278 241 423 478 444 144 963 648 383 165 134 850 445 312 387  45 871 968
 909 409 330  82 141 381 650 946 749 773 975 430 378 800]
10th Percentile: 133.1
50th Percentile (Median): 533.5
90th Percentile: 963.5
First Quartile (Q1): 342.0
Third Quartile (Q3): 796.75


ques.66 Create a NumPy array of integers and find the index of a specific element.?

In [ ]:
import numpy as np

def find_element_index(arr, element):
    indices = np.where(arr == element)[0]
    if len(indices) == 0:
        return None
    return indices[0]

arr = np.array([10, 20, 30, 40, 50])
element = 30
index = find_element_index(arr, element)

print(f"Array: {arr}")
print(f"Element {element} found at index:", index)


Array: [10 20 30 40 50]
Element 30 found at index: 2


ques.67 Generate a random NumPy array and sort it in ascending order.?

In [ ]:
import numpy as np

def generate_and_sort(size=10, low=1, high=100):
    arr = np.random.randint(low, high+1, size=size)

    sorted_arr = np.sort(arr)

    return arr, sorted_arr

arr, sorted_arr = generate_and_sort(size=10, low=1, high=100)

print("Original Array:\n", arr)
print("Sorted Array (Ascending):\n", sorted_arr)


Original Array:
 [ 48  75 100  67  57  78   6  21  83  19]
Sorted Array (Ascending):
 [  6  19  21  48  57  67  75  78  83 100]


ques.68 Filter elements >20  in the given NumPy array
 arr = np.array([12, 25, 6, 42, 8, 30])


In [ ]:
import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

filtered = arr[arr > 20]

print("Original Array:", arr)
print("Elements > 20:", filtered)

Original Array: [12 25  6 42  8 30]
Elements > 20: [25 42 30]


ques.69 Filter elements which are divisible by 3 from a given NumPy array.
  arr = np.array([1, 5, 8, 12, 15])


In [ ]:
import numpy as np

arr = np.array([1, 5, 8, 12, 15])

divisible_by_3 = arr[arr % 3 == 0]

print("Original Array:", arr)
print("Elements divisible by 3:", divisible_by_3)

Original Array: [ 1  5  8 12 15]
Elements divisible by 3: [12 15]


ques.70 Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array
 arr = np.array([10, 20, 30, 40, 50])


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

filtered = arr[(arr >= 20) & (arr <= 40)]

print("Original Array:", arr)
print("Elements ≥ 20 and ≤ 40:", filtered)


Original Array: [10 20 30 40 50]
Elements ≥ 20 and ≤ 40: [20 30 40]


ques.71 For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
 arr = np.array([1, 2, 3])


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

print("Array:", arr)
print("Byte order:", byte_order)

Array: [1 2 3]
Byte order: =


ques.72 For the given NumPy array, perform byte swapping in place using `byteswap()`
  arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

print("Original array:", arr)
print("Original byte order:", arr.dtype.byteorder)

arr.byteswap(inplace=True)

print("Array after byte swap:", arr)
print("Byte order after swap:", arr.dtype.byteorder)


Original array: [1 2 3]
Original byte order: =
Array after byte swap: [16777216 33554432 50331648]
Byte order after swap: =


ques.73 For the given NumPy array, swap its byte order without modifying the original array using newbyteorder()`.
  arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

print("Original array:", arr)
print("Original byte order:", arr.dtype.byteorder)

swapped_arr = arr.view(arr.dtype.newbyteorder())

print("Swapped array:", swapped_arr)
print("Swapped array byte order:", swapped_arr.dtype.byteorder)

print("Original array after swap:", arr)


Original array: [1 2 3]
Original byte order: =
Swapped array: [16777216 33554432 50331648]
Swapped array byte order: >
Original array after swap: [1 2 3]


ques.74 For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder()`.
  arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

print("Original array:", arr)
print("Original byte order:", arr.dtype.byteorder)
print("System byteorder:", sys.byteorder)

if sys.byteorder == 'little':
    swapped_arr = arr.view(arr.dtype.newbyteorder('>'))
else:
    swapped_arr = arr.view(arr.dtype.newbyteorder('<'))

print("Swapped array:", swapped_arr)
print("Swapped array byte order:", swapped_arr.dtype.byteorder)


Original array: [1 2 3]
Original byte order: =
System byteorder: little
Swapped array: [16777216 33554432 50331648]
Swapped array byte order: >


ques.75 For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
  arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

print("Array:", arr)
print("Array byte order:", arr.dtype.byteorder)
print("System byte order:", sys.byteorder)

if arr.dtype.byteorder == '=' or \
   (arr.dtype.byteorder == '<' and sys.byteorder == 'little') or \
   (arr.dtype.byteorder == '>' and sys.byteorder == 'big'):
    swap_needed = False
else:
    swap_needed = True

print("Byte swap needed for this system?", swap_needed)


Array: [1 2 3]
Array byte order: =
System byte order: little
Byte swap needed for this system? False


ques.76 Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`?

In [ ]:
import numpy as np

arr1 = np.arange(1, 11)
print("Original arr1:", arr1)

copy_arr = arr1.copy()
print("Copy copy_arr:", copy_arr)

copy_arr[0] = 100
print("Modified copy_arr:", copy_arr)

print("arr1 after modifying copy_arr:", arr1)


Original arr1: [ 1  2  3  4  5  6  7  8  9 10]
Copy copy_arr: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr: [100   2   3   4   5   6   7   8   9  10]
arr1 after modifying copy_arr: [ 1  2  3  4  5  6  7  8  9 10]


ques.77 Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.?

In [ ]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:\n", matrix)

view_slice = matrix[:2, :2]
print("\nView slice:\n", view_slice)

view_slice[0, 0] = 999
print("\nModified view slice:\n", view_slice)

print("\nOriginal matrix after modifying view_slice:\n", matrix)


Original matrix:
 [[8 6 2]
 [1 3 5]
 [1 6 8]]

View slice:
 [[8 6]
 [1 3]]

Modified view slice:
 [[999   6]
 [  1   3]]

Original matrix after modifying view_slice:
 [[999   6   2]
 [  1   3   5]
 [  1   6   8]]


ques.78 Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.?


In [ ]:
import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)
print("Original array_a:\n", array_a)

view_b = array_a[:2, :]
print("\nView view_b:\n", view_b)

view_b += 5
print("\nModified view_b after adding 5:\n", view_b)

print("\narray_a after modifying view_b:\n", array_a)


Original array_a:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

View view_b:
 [[1 2 3]
 [4 5 6]]

Modified view_b after adding 5:
 [[ 6  7  8]
 [ 9 10 11]]

array_a after modifying view_b:
 [[ 6  7  8]
 [ 9 10 11]
 [ 7  8  9]
 [10 11 12]]


ques.79  Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.?



In [ ]:
import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)
print("Original orig_array:\n", orig_array)

reshaped_view = orig_array.reshape(4, 2)
print("\nReshaped view (4x2):\n", reshaped_view)

reshaped_view[0, 0] = 100
print("\nModified reshaped_view:\n", reshaped_view)

print("\norig_array after modifying reshaped_view:\n", orig_array)


Original orig_array:
 [[1 2 3 4]
 [5 6 7 8]]

Reshaped view (4x2):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified reshaped_view:
 [[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]

orig_array after modifying reshaped_view:
 [[100   2   3   4]
 [  5   6   7   8]]


ques.80 Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.?

In [ ]:
import numpy as np

data = np.random.randint(1, 11, size=(3, 4))
print("Original data:\n", data)

data_copy = data[data > 5].copy()
print("\nCopied elements > 5:\n", data_copy)

data_copy[0] = 999
print("\nModified data_copy:\n", data_copy)

print("\nOriginal data after modifying data_copy:\n", data)


Original data:
 [[10  6  8  4]
 [ 5  2  8  8]
 [ 5  2  9  3]]

Copied elements > 5:
 [10  6  8  8  8  9]

Modified data_copy:
 [999   6   8   8   8   9]

Original data after modifying data_copy:
 [[10  6  8  4]
 [ 5  2  8  8]
 [ 5  2  9  3]]


ques.81 Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.?

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

add_result = A + B
print("\nA + B:\n", add_result)

sub_result = A - B
print("\nA - B:\n", sub_result)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

A - B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


ques.82 Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.?



In [ ]:
import numpy as np

C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

print("Matrix C (3x2):\n", C)
print("\nMatrix D (2x4):\n", D)

result = np.dot(C, D)
print("\nC · D (3x4):\n", result)


Matrix C (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Matrix D (2x4):
 [[ 7  8  9 10]
 [11 12 13 14]]

C · D (3x4):
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


ques.83 Create a matrix `E` and find its transpose.?

In [ ]:
import numpy as np

E = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("Original matrix E (3x2):\n", E)

E_transpose = E.T
print("\nTranspose of E (2x3):\n", E_transpose)


Original matrix E (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Transpose of E (2x3):
 [[1 3 5]
 [2 4 6]]


ques.84 Generate a square matrix `F` and compute its determinant.?

In [ ]:
import numpy as np

F = np.array([[2, 3, 1],
              [4, 5, 6],
              [7, 8, 9]])

print("Matrix F:\n", F)

det_F = np.linalg.det(F)
print("\nDeterminant of F:", det_F)

Matrix F:
 [[2 3 1]
 [4 5 6]
 [7 8 9]]

Determinant of F: 9.000000000000005


ques.85  Create a square matrix `G` and find its inverse.?

In [ ]:
import numpy as np

G = np.array([[2, 1, 3],
              [0, 1, 4],
              [5, 2, 0]])

# Step 2: Check if the matrix is invertible
determinant = np.linalg.det(G)
print("Determinant:", determinant)

if determinant != 0:
    # Step 3: Find the inverse
    G_inv = np.linalg.inv(G)
    print("Inverse of G:\n", G_inv)
else:
    print("Matrix is not invertible")